### ISSUE TITLE
[0.0.2308.061] Settings Window has no window controls

### ISSUE THREAD

**Issue by darth-crunchus** [prosthetichead/GarlicPress#61] opened 2023-08-06 17:02 UTC
**Describe the bug**
Settings window has no close button or window controls

**Screenshots**
![image](https://github.com/prosthetichead/GarlicPress/assets/27889886/0ad2c1bf-03ad-4e67-baeb-8f37e6a8a351)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]

**RG35xx (please complete the following information):**
 - GarlicOS version: [e.g.  1.4.9]

**Additional context**
GarlicPress 0.0.2308.061

**Comment by darth-crunchus** [comment] 2023-08-06 17:03
Can't even use Ctrl-W to close it.

**Comment by baloneyninja** [comment] 2023-08-06 23:42
I also notice that also  edit skin settings are also missing window controls.

**Comment by baloneyninja** [comment] 2023-08-06 23:43
> Can't even use Ctrl-W to close it.
I found Alt+F4 works.

**Comment by hypist** [comment] 2023-08-07 01:26
Currently experiencing the same issue.

I'm also running Windows 11. No issues with prior releases as far as missing window controls. This release, they seemed to have disappeared.

CTRL-W seems to work for closing the window, but it doesn't appear to save the settings (I could be wrong).

**Comment by prosthetichead** [comment] 2023-08-07 02:14
Few reports of this on reddit also wondering if it's related to dpi scales? I will test and release a new version to fix tonight after work. Sorry about that.

**Comment by hypist** [comment] 2023-08-07 07:50
> Few reports of this on reddit also wondering if it's related to dpi scales? I will test and release a new version to fix tonight after work. Sorry about that.

Yep, that's exactly it.

Just went and tried changing scaling through Windows Display settings and sure enough that's the issue.

100% scaling works as intended, but anything beyond that seems to break the UI.

**Comment by darth-crunchus** [comment] 2023-08-07 10:35
> Few reports of this on reddit also wondering if it's related to dpi scales? I will test and release a new version to fix tonight after work. Sorry about that.

Hey, stuff happens.  Thanks for for giving us this tool.

**Closed** 2023-08-07 11:57 UTC
Labels: bug
